### PR TITLE
Updated IO-methods.R and added extend_metagenomeSeq.R

### PR DESCRIPTION
**Pull request by jnpaulson**
Added the fix to the `import_biom` function and added a `phyloseq_to_metagenomeSeq` function. Upticked.

### CODE REVIEW

**Comment by joey711** [comment]
@jnpaulson 
Can you separate this out into two different PRs? One for the metagenomeSeq export, and one for the biom import fix? These are two totally different things.

Secondly, I'm not going to add yet another complicated dependency to phyloseq, especially not just to support a single exporter function to metagenomeSeq. I'm not picking on you, I just told the same thing to someone else who had submitted a PR for a GUniFrac function support, by adding a dependency to the GUniFrac package. 

The details escape me, but there should be a way to do this as a "Suggests" level dependency, so that it is not necessary to install metagenomeSeq to use phyloseq, or to load any aspect of the metagenomeSeq namespace just to load phyloseq. Make sense?

There are a number of different ways to do this. Maybe roll back your PR to just the biom thing, and then ping here, or simply resubmit two new PRs where this has been separated out. 

Thanks, Joe!

**Comment by jnpaulson** [comment]
Sounds good - I'll just resubmit two PRs. 

You bring up a good point, currently there are quite a few dependencies that seem to make `phyloseq` take a while in loading. Let me know if you'd like help restructuring pieces.

**Comment by joey711** [comment]
I would be very supportive of fixes like that. DESeq2 especially. There's some time to get this into the next BioC release if we're careful and don't break anything O:-). I think DESeq2 is adding a lot of the slowness, however. It should be the first to migrate to "Suggests" level dependency.

**Comment by jnpaulson** [comment]
Separating them (will keep updating this):
https://github.com/joey711/phyloseq/pull/531

Let me know if you want me to add upticks. Otherwise, I'll let you do that.

**Pull request closed without merging**
