### PR TITLE
Add size-parsing functionality to the import_usearch_uc function. Thi…

### PR DESCRIPTION
**Pull request by zachcp**
…s allows users of the USearch program to take advantage of size annotations that USearch adds to fasta files in its pipeline; a suffix like "size=234;". This is pulled out by regex and the casting is then based on the sum of the size column.

Hi Joey711,

This is a pull request to allow users to pull in the size annotation from a usearch file if they have been using the Usearch-based pipeline. Its pretty straightforward, but the main tricky issue was the regex to pull out the size. I tried a few different methods and got the `str_match` function to work so I was happy with that. However, it does then drag in another package (stringr). Certainly open to alternatives but my regex-fu came up short. 

Thanks Again for your great work,
zach p

### CODE REVIEW

**Comment by joey711** [comment]
stringr is great, but I'd rather not add yet another package dependency.

Incidentally, I did this using R regex a few months ago... I'm not sure if I have the code laying around, but I can give that a try. I like the added IO support for the usearch suite, so happy to get this in here.

Thanks!

**Comment by zachcp** [comment]
Great! Glad you like the functionality. 

I hear you about the dragging in of extra packages. If you have that extraction regex, that would be great. I can also give another stab with base R.

Actually, I think the following may suffice:

```r
as.numeric( sub(".*size=([0-9]+);?$", "\\1", read) )
```

I'll try it out.

zcp

**Comment by joey711** [comment]
What I like to do in these situations is usually define a regex string (or function) as a default that handles the expected format case, leaving it open to the user to replace that string/function if they have a different unsupported format.

**Comment by zachcp** [comment]
@joey711 - thats an excellent idea and not hard to code up. will do.

**Comment by zachcp** [comment]
@joey711 not sure whats going on with circle CI but travis builds fine. hope this does this trick.

one thought on builds: they take a loooong time and it looks like many dependencies get built from scratch every time. maybe its worth considering turning on [package caching](https://docs.travis-ci.com/user/languages/r)

**Pull request closed without merging**
