### PR TITLE
add a merge_function to create the new OTU table

### PR DESCRIPTION
**Pull request by zachcp**
WIP. Passes all the tests and gives a ~3X speedup. Probably due to the fact that the only speed gains are obtained at the level of the OTU table. If you also modify the TaxTable in the same way it could be even better. 

heres my numbers for patched and unpatched:

```{r}


library(phyloseq)
> data("GlobalPatterns")
> GP <- GlobalPatterns
> 
> # Test Taxtable: Don't Expect a Speed Change
> ptm <- proc.time()
> tg <- tax_glom(tax_table(GP),  taxrank="Family") 
> proc.time() - ptm
   user  system elapsed 
  6.429   0.811   7.396 
> 
> # Test Physeq: Expect Speedup on the OTU Table
> ptm <- proc.time()
> tg <- tax_glom(GP, taxrank="Family") 
> proc.time() - ptm
   user  system elapsed 
229.361   5.154  51.702 

#Patched Version
> library(phyloseq)
> data("GlobalPatterns")
> GP <- GlobalPatterns
> 
> # Test Taxtable:
> ptm <- proc.time()
> tg <- tax_glom(tax_table(GP),  taxrank="Family") 
> proc.time() - ptm
   user  system elapsed 
  7.324   0.761   8.223 
> 
> # Test Physeq
> ptm <- proc.time()
> tg <- tax_glom(GP, taxrank="Family") 
> proc.time() - ptm
   user  system elapsed 
134.123  17.776 155.551 
```

### CODE REVIEW

**Comment by zachcp** [comment]
in reference to #537 and #517

**Comment by zachcp** [comment]
Right now its split/apply/recombine of the OTU table and then, if both a TAX and OTU table are there, reuse the OTU table to select tax tree rows. 

On the GP dataset this is a ~5x increase in speed. 
https://gist.github.com/zachcp/4cff2a9752ab3f5929a1

Room for improvement: 

1.  reuse the OTU-table Indices to subset ALL relevant classes (taxonomyTable, phy_tree, XStringSet). This is a little trickier than it sounds. 
2.  are there faster ways to split than I currently use? matrix instead of dataframe?

**Comment by joey711** [comment]
data.table does these sorts of splits very fast because it uses sorted-keyed indexing instead of vector scan. Not sure of the performance comparison in this exact context, though.

It just dawned on me that there is a problem in your proposed design for taxonomy. In the current approach, phyloseq is "smart" and modifies the taxonomy table according to a set of rules that respects the taxonomic hierarchy. When merging two or more taxa, the taxonomy is only non-NA to the most specific common rank. Simply grabbing the taxonomy of the representative taxa ID would lose, and in some cases badly misrepresent, the taxonomy of the merged group.

I can think of some ways to keep this behavior while still using your speedup.

**Comment by joey711** [comment]
(p.s. it is strange that your PR passes all tests. I thought I had included tests for this taxonomy-merge behavior in the testthat tests. Perhaps not, or the tests are not specific enough.)

**Comment by zachcp** [comment]
yeah, now I see what you mean - its in the taxonomyTable `merge_taxa` function. I did not address that at all.  I adopted this approach after getting my original function working fine on otu-tables but failing with phyloseq objects that had both otu_tables and tax_tables. The default behavior of `merge_taxa` is different for those two classes. So I was looking for a way to make them consistent.  

The approach you are suggesting would require processing the taxonomy table and only using the OTU indices to verify consistency. Hmmm....

**Comment by zachcp** [comment]
Also, I should be able to swap the vanilla R for data.table in the OTU summing calc for a perf bump.  [for my notes](http://www.brodieg.com/?p=7) something like: `dt[, lapply(.SD, sum), by="tax"]`

**Comment by zachcp** [comment]
I'm going to close this for now. I may revisit it with the necessary taxonomy improvements but as is its a no-go.

**Pull request closed without merging**
